services:
    # Kontener z aplikacją Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - ./:/var/www/html
        depends_on:
            - db

    # Nginx jako serwer WWW
    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        ports:
            - "8000:80"  # Mapowanie na lokalny port 8000
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    # Baza danych MySQL
    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootsecret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: swagger-ui
        ports:
            - "8888:8080"
        environment:
            SWAGGER_JSON: /swagger.yaml
        volumes:
            - ./swagger.yaml:/swagger.yaml

    # phpMyAdmin - narzędzie do zarządzania bazą MySQL
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
            - db
        ports:
            - "8080:80"          # http://localhost:8080
        environment:
            PMA_HOST: db
            PMA_USER: laravel
            PMA_PASSWORD: secret

volumes:
    db_data:
